TheBakery/Controllers/RequestInformationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheBakery.Models;
using TheBakery.ViewModels;


namespace TheBakery.Controllers
{
    public class RequestInformationController : Controller
    {

        //private TheBakeryDBEntities _entities = new TheBakeryDBEntities();

        // GET: RequestInformation
        // we use this to restrict people from only being able to enter contact information if 
        // they are logged in. 
        [Authorize]
        public ActionResult RequestInformation()
        {
            return View();
        }


        //[HttpPost]
       // public ActionResult FormOne(string name)
        //{
            //Do something
            //return RedirectToAction("RequestInfoSubmitted");
        //}

        
        // Called by FormOne 
        [HttpPost] 
        public ActionResult RequestInfoSubmitted(string userName, string firstName, string lastName, string email, string emailConfirm, string age, string comments)
        {
            
            


            // Set up our ViewModel
            ContactInfo myContactInfo = new ContactInfo();
            myContactInfo.UserName = this.Request["userName"];
            myContactInfo.FirstName = this.Request["firstName"];
            myContactInfo.LastName = this.Request["lastName"];
            myContactInfo.Email = this.Request["email"];
            myContactInfo.EmailConfirm = this.Request["emailConfirm"];
            //myContactInfo.Age.ToString();
            //age.ToString();
            myContactInfo.Age = this.Request["age"];
            myContactInfo.Comments = this.Request["comments"];
            InsertContact(userName, firstName, lastName, email, emailConfirm, age, comments);

            //var db = Database.SetInitializer<TheBakeryDB>(new DropCreateDatabaseIfModelChanges<TheBakeryDB>());
            //var insertCommand = "INSERT INTO ContactInformation (username, firstName, lastName, email, age, comments) VALUES(@0, @1, @2, @3, @4, @5)";
            //db.Execute(insertCommand, userName, firstName, lastName, email, age, comments);
            

            return View(myContactInfo);

        }


        private void InsertContact(string userName, string firstName, string lastName, 
            string email, string emailConfirm, string age, string comments)
        {
            
        }

        






        


    }
}

TheBakery/Views/RequestInformation/RequestInfoSubmitted.cshtml
@model TheBakery.ViewModels.ContactInfo


@{
    ViewBag.Title = "RequestInfoSubmitted";
}

<h2>Request Information Submitted</h2>
<h3>You have successfully submitted your form!</h3>
<h4>Here is your data:</h4>
<ul>

    <li>Username: @Model.UserName</li>
    <li>First Name: @Model.FirstName</li>
    <li>Last Name: @Model.LastName</li>
    <li>Email: @Model.Email</li>
    <li>Age: @Model.Age</li>
    <li>Comments: @Model.Comments</li>

</ul>

<!--<form action="/RequestInformation/RequestInfoSubmitted" method="get">
    
    


</form>
    -->
<!-- m => m.name)-->

TheBakery/Views/RequestInformation/RequestInformation.cshtml
@{
    ViewBag.Title = "Request Information";
}


@model TheBakery.ViewModels.ContactInfo


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="bootstrap/bootstrap-2.3.1.min.js"></script>


<h2>Request Information</h2>

@using (Html.BeginForm("RequestInfoSubmitted", "RequestInformation", FormMethod.Post))
{
 
    @Html.LabelFor(m => m.UserName)
    <br />

    @Html.TextBoxFor(m => m.UserName);
    <br />

    @Html.ValidationMessageFor(m => m.UserName);
    <br />
    <br />


    @Html.LabelFor(m => m.FirstName) 
    <br />
    
    @Html.TextBoxFor(m => m.FirstName);
    <br />
    
    @Html.ValidationMessageFor(m => m.FirstName);
    <br />
    <br />
    
    @Html.LabelFor(m => m.LastName);
    <br />
    
    @Html.TextBoxFor(m => m.LastName);
    <br />
    
    @Html.ValidationMessageFor(m => m.LastName);
    <br />
    <br />

    @Html.LabelFor(m => m.Email);
    <br />

    @Html.TextBoxFor(m => m.Email);
    <br />
    
    @Html.ValidationMessageFor(m => m.Email);
    <br />
    <br />
    
    @Html.LabelFor(m => m.EmailConfirm);
    <br />
    
    @Html.TextBoxFor(m => m.EmailConfirm);
    <br />
    
    @Html.ValidationMessageFor(m => m.EmailConfirm);
    <br />
    <br />
    
    
    @Html.LabelFor(m => m.Age)
    <br />
    
    @Html.TextBoxFor(m => m.Age)
    <br />
    
    @Html.ValidationMessageFor(m => m.Age)
    <br />
    <br />
    
    
    @Html.LabelFor(m => m.Comments)
    <br />

    @Html.TextAreaFor(m => m.Comments);
    <br />

    <button type="submit">Submit</button>
     
    //<input type="text" name="name" />

    //<input type="submit" value="Submit" />

    
}

<!--
<form action="/RequestInformation/RequestInfoSubmitted" method="post" >
   <!--<input type="text" name="name" />
    
    
    <input type="submit" value="Submit" />
</form>-->
    